# =============================================
# Site settings
# =============================================

title: Logsearch
email: your-email@domain.com
description: The easiest way to search logs using the power of ELK
baseurl: ""
url: "http://www.logsearch.io/"
github_username:  logsearch

# =============================================
# Build settings
# =============================================

markdown: kramdown