title: Logsearch
description: The easiest way to search logs using the power of ELK
url: "http://www.logsearch.io"
github_username: logsearch
permalink: "/blog/:year/:month/:title:output_ext"
exclude:
  - "Dockerfile"
  - "README.md"
defaults:
  -
    scope:
      path: "blog"
    values:
      layout: "post"
  -
    scope:
      path: "docs"
    values:
      layout: "docs-default"
  -
    scope:
      path: "docs/boshrelease"
    values:
      repo_github: "https://github.com/logsearch/logsearch-boshrelease"
      prenav:
        - [ "Documentation", "/docs/" ]
        - [ "Logsearch (BOSH)", "/docs/boshrelease/" ]
  -
    scope:
      path: "docs/shipper-boshrelease"
    values:
      repo_github: "https://github.com/logsearch/logsearch-shipper-boshrelease"
      prenav:
        - [ "Documentation", "/docs/" ]
        - [ "Logsearch Shipper (BOSH)", "/docs/shipper-boshrelease/" ]
  -
    scope:
      path: "docs/filters-common"
    values:
      repo_github: "https://github.com/logsearch/logsearch-filters-common"
      prenav:
        - [ "Documentation", "/docs/" ]
        - [ "Filters", "/docs/filters-common/" ]
  -
    scope:
      path: "docs/workspace"
    values:
      repo_github: "https://github.com/logsearch/workspace"
      prenav:
        - [ "Documentation", "/docs/" ]
        - [ "Workspace", "/docs/workspace/" ]
